### ISSUE TITLE
数据标注问题

### ISSUE THREAD

**Issue by speedcell4** [450586509/DLNLP#1]
难道不应该是像POS tagging一样每一个字一个tag么？为什么要整句一个tag？

`小/S 明/E 喜/S 欢/E 自/S 然/M 语/M 言/M 处/M 理/E`

**Comment by speedcell4** [comment]
或者你的意思是按LSTM的视角，每读一个字输出一个tag？

**Comment by 450586509** [comment]
我是你说的第二种方法。

**Comment by 450586509** [comment]
如果按照LSTM视角，这种输入输出数据是怎么构造？我以前做句子分类的时候，把整个句子通过LSTM encode 为一个向量，再用逻辑回归（sigmoid神经元）。

**Comment by speedcell4** [comment]
头像帅炸了

**Comment by speedcell4** [comment]
嘛，其实无所谓，对于LSTM还不是没读一个字出一个tag

**Comment by 450586509** [comment]
嗯，也可以理解为机器翻译吧，将一个句子翻译成BEMS串。

**Comment by 450586509** [comment]
现在已经解决了数据输入输出的问题。^_^。
